version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-server
    ports:
      - "9411:9411"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-volume

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always

  discovery:
    image: microservices/discovery
    container_name: discovery
    depends_on:
      - graphite
      - zipkin
    environment:
      - ZIPKIN_HOST=zipkin
    ports:
      - "8761:8761"

  apigateway:
    image: microservices/apigateway
    container_name: apigateway
    depends_on:
      - discovery
      - graphite
    links:
      - discovery
    environment:
      - EUREKA_URI=discovery
    ports:
      - "8765:8765"

  one:
    image: microservices/one
    container_name: service-one
    depends_on:
      - graphite
      - discovery
      - apigateway
    links:
      - discovery
      - graphite
    environment:
      - EUREKA_URI=discovery
      - METRIC_OBSERVER_URI=graphite

  two:
    image: microservices/two
    container_name: service-two
    depends_on:
      - graphite
      - discovery
      - apigateway
      - one
    links:
      - graphite
      - discovery
      - one
    environment:
      - EUREKA_URI=discovery
      - METRIC_OBSERVER_URI=graphite

volumes:
  grafana-volume:
    external: true