server:
  port: 8081

spring:
  application:
    name: apigateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    properties-from-dynamic:
      path: /properties-from-dynamic
      url: http://localhost:8082/properties-from-dynamic
      
#    foos:
#      path: /foos/**
#      url: http://localhost:8082/spring-zuul-foos-resource/foos