spring:
  application:
    name: two
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URI:localhost}:8761/eureka
#      defaultZone: """${EUREKA_URI:http://localhost:8761/eureka}